### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by Tortoise17** [olafrv/ai_chat_llama2#3]
This is a nice documentation and guide to use such way of LLAMA2 model for chatbot. 
I want to ask that is there any easy way to finetune it for a customized data chatbot for questioning answering? Please if you can guide.

**Comment by olafrv** [comment]
I haven't had time to check if the way I want to do it (easy) with Autotrain is working by now.
See what I mean here: https://github.com/olafrv/ai_chat_llama2#model-training-draft

**Comment by olafrv** [comment]
I left a few samples of training with tfl and autotrain, they seem to work, but require way more RAM/VRAM than I have:
https://github.com/olafrv/ai_chat_llama2/blob/342d7654046904b465f3048c02310b364d80b222/Makefile#L58
